<?php

/* @see _themekit_pop_parent() */
define('THEMEKIT_POP_PARENT', '_themekit_pop_parent');

/**
 * Implements hook_theme()
 *
 * @return array
 */
function themekit_theme() {
  return [
    /* @see theme_themekit_container() */
    'themekit_container' => [
      'render element' => 'element',
      'file' => 'themekit.theme.inc',
    ],
    /* @see theme_themekit_item_containers() */
    'themekit_item_containers' => [
      'render element' => 'element',
      'file' => 'themekit.theme.inc',
    ],
    /* @see theme_themekit_link_wrapper() */
    'themekit_link_wrapper' => [
      'render element' => 'element',
      'file' => 'themekit.theme.inc',
    ],
    /* @see theme_themekit_item_list() */
    'themekit_item_list' => [
      'render element' => 'element',
      'file' => 'themekit.theme.inc',
    ],
    /* @see theme_themekit_separator_list() */
    'themekit_separator_list' => [
      'render element' => 'element',
      'file' => 'themekit.theme.inc',
    ],
  ];
}

/**
 * Implements hook_element_info()
 *
 * @return array
 */
function themekit_element_info() {
  return [
    'themekit_container' => [
      /* @see theme_themekit_container() */
      '#theme_wrappers' => ['themekit_container'],
    ],
    'themekit_link_wrapper' => [
      /* @see theme_themekit_link_wrapper() */
      '#theme_wrappers' => ['themekit_link_wrapper'],
    ],
  ];
}

/**
 * Callback for $element['#process'].
 *
 * @param array $element
 *
 * @return array
 */
function _themekit_pop_parent(array $element) {
  array_pop($element['#parents']);
  return $element;
}
